## Trabajo grupal 3: Grupo 1

In [69]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [70]:
junin = pd.read_excel("../data/Region_Junin.xlsx")

In [71]:
junin.drop(junin.columns[0], axis=1, inplace=True)  # Drop the first column to show better
junin

,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,72,72,0,0,0,0,35,39,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0

##### Pregunta 1: Obtener el nombre de todas las variables

In [72]:
junin.columns    # Show all the head columns

Index(['Region', 'District', 'Place', '4_6_years_men', '4_6_years_women',
       '4_6_years_total', '6_14_years_men', '6_14_years_women',
       '6_14_years_total', 'man_read', 'women_read', 'total_read',
       'men_not_read', 'women_not_read', 'total_not_read', 'man_write',
       'women_write', 'total_write', 'men_not_write', 'women_not_write',
       'total_not_write', 'instruction_men', 'instruction_women',
       'instruction_total', 'no_instruction_men', 'no_instruction_women',
       'no_instruction_total', 'finished_instr_men', 'finished_instr_women',
       'finished_instr_total', 'not_finished_instr_men',
       'not_finished_instr_women', 'not_finished_instr_total', 'peruvian_men',
       'peruvian_women', 'foreign_men', 'foreign_women', 'whites', 'natives',
       'mestizos', 'blacks'],
      dtype='object')

In [73]:
type(junin.columns)   # Show the type

pandas.core.indexes.base.Index

##### Pregunta 2: Mostrar el tipo de variables (type) así como presentar los principales estadísticos.

In [74]:
junin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Region                    197 non-null    object
 1   District                  197 non-null    object
 2   Place                     197 non-null    object
 3   4_6_years_men             197 non-null    int64
 4   4_6_years_women           197 non-null    int64
 5   4_6_years_total           197 non-null    int64
 6   6_14_years_men            197 non-null    int64
 7   6_14_years_women          197 non-null    int64
 8   6_14_years_total          197 non-null    int64
 9   man_read                  197 non-null    int64
 10  women_read                197 non-null    int64
 11  total_read                197 non-null    int64
 12  men_not_read              197 non-null    int64
 13  women_not_read            197 non-null    int64
 14  total_not_read            197 non-null    int64
 15  man_write                 197 non-null    int64
 16  women_write               197 non-null    int64
 17  total_write               197 non-null    int64
 18  men_not_write             197 non-null    int64
 19  women_not_write           197 non-null    int64
 20  total_not_write           197 non-null    int64
 21  instruction_men           197 non-null    int64
 22  instruction_women         197 non-null    int64
 23  instruction_total         197 non-null    int64
 24  no_instruction_men        197 non-null    int64
 25  no_instruction_women      197 non-null    int64
 26  no_instruction_total      197 non-null    int64
 27  finished_instr_men        197 non-null    int64
 28  finished_instr_women      197 non-null    int64
 29  finished_instr_total      197 non-null    int64
 30  not_finished_instr_men    197 non-null    int64
 31  not_finished_instr_women  197 non-null    int64
 32  not_finished_instr_total  197 non-null    int64
 33  peruvian_men              197 non-null    int64
 34  peruvian_women            197 non-null    int64
 35  foreign_men               197 non-null    int64
 36  foreign_women             197 non-null    int64
 37  whites                    197 non-null    int64
 38  natives                   197 non-null    int64
 39  mestizos                  197 non-null    int64
 40  blacks                    197 non-null    int64
dtypes: int64(38), object(3)
memory usage: 63.2+ KB

In [75]:
junin.describe()    # The principal stadistic

,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,women_read,total_read,men_not_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
count,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,...,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000
mean,16.979695,15.345178,32.324873,79.005076,62.482234,141.538071,34.654822,11.705584,46.360406,61.294416,...,79.238579,172.675127,95.918782,77.664975,0.030457,0.010152,9.893401,110.558376,52.583756,0.776650
std,22.571419,21.618979,43.489455,99.837291,90.879972,188.535210,51.091581,34.676708,83.291516,84.511046,...,111.799104,220.657751,120.177520,110.539722,0.265511,0.100501,39.677190,131.094774,123.120065,7.584952
min,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,4.000000,8.000000,25.000000,19.000000,42.000000,2.000000,0.000000,2.000000,22.000000,...,25.000000,50.000000,31.000000,25.000000,0.000000,0.000000,0.000000,40.000000,0.000000,0.000000
50%,10.000000,9.000000,20.000000,55.000000,41.000000,91.000000,21.000000,0.000000,23.000000,41.000000,...,50.000000,108.000000,65.000000,50.000000,0.000000,0.000000,0.000000,73.000000,3.000000,0.000000
75%,20.000000,18.000000,39.000000,88.000000,73.000000,160.000000,42.000000,7.000000,50.000000,65.000000,...,94.000000,197.000000,103.000000,91.000000,0.000000,0.000000,0.000000,143.000000,48.000000,0.000000
max,184.000000,184.000000,368.000000,950.000000,957.000000,1907.000000,317.000000,225.000000,542.000000,817.000000,...,1089.000000,2164.000000,1132.000000,1141.000000,3.000000,1.000000,348.000000,1367.000000,808.000000,92.000000

##### Pregunt 3: Verifique si las columnas presentan missing values

In [76]:
junin.isnull().sum()  # To know if the columns have missing values

Region                      0
District                    0
Place                       0
4_6_years_men               0
4_6_years_women             0
4_6_years_total             0
6_14_years_men              0
6_14_years_women            0
6_14_years_total            0
man_read                    0
women_read                  0
total_read                  0
men_not_read                0
women_not_read              0
total_not_read              0
man_write                   0
women_write                 0
total_write                 0
men_not_write               0
women_not_write             0
total_not_write             0
instruction_men             0
instruction_women           0
instruction_total           0
no_instruction_men          0
no_instruction_women        0
no_instruction_total        0
finished_instr_men          0
finished_instr_women        0
finished_instr_total        0
not_finished_instr_men      0
not_finished_instr_women    0
not_finished_instr_total    0
peruvian_men                0
peruvian_women              0
foreign_men                 0
foreign_women               0
whites                      0
natives                     0
mestizos                    0
blacks                      0
dtype: int64

##### Pregunta 4: Cambie el nombre de las siguientes variables: Place : comunidad, men_not_read: nlee_hombre, women_not_read: nlee_mujer,  total_not_read: ntotal_lee, men_not_write: nesc_hombre, women_not_write: nesc_hombre, total_not_write: nesc_total.

In [77]:
junin.rename(columns = {'Place':'comunidad', 'men_not_read':'nlee_hombre', 'women_not_read':'nlee_mujer', 'men_not_write':'nesc_hombre', 
                       'women_not_write':'nesc_mujer', 'total_not_write':'nesc_total'}, inplace = True)
junin

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,72,72,0,0,0,0,35,39,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0

##### Pregunta 6: Muestre los valores únicos de las siguientes variables ( comunidad , District)

In [78]:
junin.comunidad.unique()

array(['C.CIUDAD DEL CERRO', 'P.YANACANCHA', 'VICO', 'RANCA', 'PASCO',
       'QUIRLACOCHA', 'CAJAMARQUILLA', 'CAICO', 'ROCO', 'C.SACRA FAMILIA',
       'P.QUINUA', 'H.PARIAHUANCA', 'P.SULLUMARCA', 'H.SAN ANDRÉS',
       'P.HUALLAY', 'C.HUAYCHAO', 'COCHAMARCA', 'P.CHACAYÁN',
       'VILCABAMBA', 'CUCHES', 'CHANGO', 'MITO', 'ANTAPIRCA', 'P.CAYNA',
       'A. COLPAS', 'P.YACAS', 'C.MASQUIN', 'P.YAMOR', 'PÁUCAR', 'TANGOR',
       'QUIO', 'CAURY', 'CHUCCHUC', 'COQUIN', 'A.YAPOC', 'P.YANAHUANCA',
       'HUAYLACIRCA', 'HUARANTAMBO', 'ANDUCHACA', 'VILLO', 'MICHIVILCA',
       'PILLAO', 'YACÁN', 'TÁPUC', 'CHAUPIMARCA', 'P.OXAPAMPA', 'P.JAUJA',
       'A.CHUNÁN', 'C.PACAPACHA', 'HUANCAS', 'A.HUERTAS', 'PACA', 'MASMA',
       'ATAURA', 'HUALÁ', 'JULCÁN', 'P.RICRÁN', 'A.PAUCÁN', 'P.APATA',
       'HUAMALÍ', 'A.SAN LORENZO', 'PACUCHO', 'P.ORCOTUNA', 'A.VICSO',
       'TISTES', 'P.HUARIPAMPA', 'A.PARCO', 'PACCHA', 'CANCHAPUNCO',
       'C.ULLUSCA', 'CANCHAS', 'P.MUQUIYAUYO', 'MUQUI', 'P.ACOLLA',
       'MARCO', 'TRAGADERO', 'CHOCÓN', 'ACAYA', 'YAUJAILLO', 'CURICACA',
       'P.CINCOS', 'C.LLACUARI', 'P.HUANCARÍ', 'C.CHALHUAS', 'ARAMACHAY',
       'P.MITO', 'A.CHAMBARÁ', 'C.QUICHA', 'HUACHAC', 'A.ACO',
       'P.LLOCLLAPAMPA', 'VISCAS ESPERANZA', 'CONCHAILLO', 'MATA-CHICO',
       'MATA-GRANDE', 'P.CONCEPCIÓN', 'SANTA ROSA DE OCOPA', 'HUANTAR',
       'A.ALAYO', 'C.SAN ANTONIO DE CARICANCHO', 'SANTO DOMINGO',
       'P.CÓMAS', 'C.CHUPA', 'COCHAS', 'P.MATAHUASI', 'P.HUANCAYO',
       'CAJAS', 'P.CHUPACA', 'A.ISCOS', 'ANTAPAMPA', 'HUAUSCA GRANDE',
       'SAN JUAN DE TARPA', 'YANACANCHA', 'COPCA', 'HUAYAN', 'HUAMANCACA',
       'PILCOMAYO', 'AHUAC', 'ACAC', 'P.SAN GERÓNIMO', 'HUALHUAS',
       'SAN PEDRO DE SAÑO', 'QUICHUAY', 'CASACANCHA', 'A.INGENIO',
       'P.SANTA CRUZ DE QUILCAY', 'RANGRA', 'P.SAPALLANGA', 'A.LA PUNTA',
       'P.PUCARÁ', 'C.PATALÁ', 'MARCAVALLE', 'COCHARCAS', 'P.CHONGOS',
       'C.TURPAC Y TINYARI', 'SOCOS', 'PUMPUNGA', 'CHUPURO',
       'CARHUAPACHA', 'A.HUAMANCACA', 'P.SICAYA', 'A.HUANCHAC',
       'C.CACHICAMARCA', 'P.COLCA', 'A.CHACAPAMPA', 'HUASICANCHA',
       'CUCHO', 'CHILIAY', 'POTACA', 'LARIA', 'CHONGOS ALTO',
       'P.HUAYUCACHI', 'HUAMANMARCA', 'VIQUES', 'CACAS', 'HUARAPUQUIO',
       'CULLHUAS', 'RETAMA', 'PACHA', 'P.TARMA', 'MACO', 'MULLUERO',
       'ANDAMARCA', 'CHANCHA', 'TARMATAMBO', 'P.JUNÍN', 'HUASAHUASY',
       'PARI', 'YANEC', 'CHUPÁN', 'ACONCOCHA', 'ONDORES', 'P.ACOBAMBA',
       'PICOY', 'C.HUARACAYO', 'A.PALCA', 'C.HUAILAHUICHÁN',
       'P.PALCAMAYO', 'P.OROYA', 'HUAYNACANCHA', 'HUAYHUAY',
       'P.CARHUAMAYO', 'ULCUMAYO', 'P.SAN RAMÓN', 'LA MERCED',
       'P.VISCATÁN', 'PAN DE AZÚCAR', 'SUITUCANCHA', 'CHACAPALCA',
       'P.POMACOCHA', 'PACHACHACA', 'YAULI', 'MINAS DE MOROCOCHA'],
      dtype=object)

In [79]:
junin.District.unique()

array(['CIUDAD DEL CERRO', 'HUAYLLAY', 'CHACAYÁN', 'CAYNA', 'YANAHUANCA',
       'NINACACA', 'JAUJA', 'APATA', 'ORCOTUNA', 'HUARIPAMPA',
       'MUQUIYAUYO', 'ACOLLA', 'CINCOS', 'MITO', 'LLOCLLAPAMPA',
       'CONCEPCIÓN', 'COCHAS', 'MATAHUASI', 'HUANCAYO', 'CHUPACA',
       'SAN GERÓNIMO', 'SAPALLANGA', 'CHONGOS', 'SICAYA', 'COLCA',
       'HUAYUCACHI', 'TARMA', 'JUNÍN', 'ACOBAMBA', 'OROYA', 'CARHUAMAYO',
       'CHANCHAMAYO', 'VITOC', 'CHACAPALCA', 'YAULI'], dtype=object)

##### Pregunta 7: Borrar las varaibles finished_instr_total, finished_instr_men y finished_instr_women

In [80]:
junin = junin.drop(['finished_instr_total', 'finished_instr_men', 'finished_instr_women'], axis=1)  # Use axis 1 to drop the columns
junin

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,209,544,361,216,1,1,4,284,290,1
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,50,100,50,50,0,0,0,100,0,0
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,25,72,47,25,0,0,0,69,3,0
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,25,50,25,25,0,0,0,25,25,0
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,72,72,0,0,0,0,35,39,0
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,7,23,16,7,0,0,0,21,2,0
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,8,30,22,8,0,0,0,4,26,0
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,37,103,76,44,0,0,37,14,69,0
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,30,126,96,30,0,0,1,118,7,0

##### Pregunta 8: Crear columnas con las siguiente información: el % de mujeres que no escriben ni leen, % de varones que no escriben ni leen y % de nativos respecto al total de la población.

In [81]:
junin['Total_poblacion']=junin['peruvian_men']+junin['peruvian_women']+junin['foreign_men']+junin['foreign_women']

In [82]:
junin['%_women_nread_nwrite'] = junin['no_instruction_women'] * 100 / junin['Total_poblacion']

In [83]:
junin['%_men_nread_nwrite'] = junin['no_instruction_men'] * 100 / junin['Total_poblacion']

In [84]:
junin['%_natives'] = junin['natives'] * 100 / junin['Total_poblacion']

In [85]:
junin

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,foreign_men,foreign_women,whites,natives,mestizos,blacks,Total_poblacion,%_women_nread_nwrite,%_men_nread_nwrite,%_natives
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,1,1,4,284,290,1,579,32.469775,51.986183,49.050086
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,0,0,0,100,0,0,100,50.000000,45.000000,100.000000
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,0,0,0,69,3,0,72,34.722222,9.722222,95.833333
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,0,0,0,25,25,0,50,50.000000,0.000000,50.000000
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,0,0,0,37,13,0,50,50.000000,50.000000,74.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,42,...,0,0,0,35,39,0,72,0.000000,75.000000,48.611111
193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,8,...,0,0,0,21,2,0,23,30.434783,13.043478,91.304348
194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,7,...,0,0,0,4,26,0,30,6.666667,23.333333,13.333333
195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,41,...,0,0,37,14,69,0,120,16.666667,23.333333,11.666667
196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,8,...,0,0,1,118,7,0,126,23.809524,73.015873,93.650794

##### Pregunta 9: Crear una base de datos con la siguiente información:

###### a. Quedarse con la información de los distritos de Ciudad del Cerro, Jauja, Acolla, San Gerónimo, Tarma, Oroya y Concepción

In [86]:
junin1 = junin[junin["District"].isin(["CIUDAD DEL CERRO","JAUJA","ACOLLA","SAN GERÓNIMO",
                                      "TARMA","OROYA","CONCEPCIÓN"])] # filter by variables's values
junin1

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,foreign_men,foreign_women,whites,natives,mestizos,blacks,Total_poblacion,%_women_nread_nwrite,%_men_nread_nwrite,%_natives
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,1,1,4,284,290,1,579,32.469775,51.986183,49.050086
1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,30,...,0,0,0,100,0,0,100,50.000000,45.000000,100.000000
2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,25,...,0,0,0,69,3,0,72,34.722222,9.722222,95.833333
3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,25,...,0,0,0,25,25,0,50,50.000000,0.000000,50.000000
4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,3,...,0,0,0,37,13,0,50,50.000000,50.000000,74.000000
5,JUNIN,CIUDAD DEL CERRO,QUIRLACOCHA,6,7,13,44,43,87,13,...,0,0,0,65,35,0,100,50.000000,38.000000,65.000000
6,JUNIN,CIUDAD DEL CERRO,CAJAMARQUILLA,9,8,17,31,39,70,0,...,0,0,0,87,0,0,87,54.022989,45.977011,100.000000
7,JUNIN,CIUDAD DEL CERRO,CAICO,18,23,41,90,77,167,34,...,0,0,4,175,29,0,208,40.384615,37.019231,84.134615
8,JUNIN,CIUDAD DEL CERRO,ROCO,7,4,11,42,19,61,0,...,0,0,0,70,2,0,72,31.944444,68.055556,97.222222
9,JUNIN,CIUDAD DEL CERRO,C.SACRA FAMILIA,16,8,24,26,25,51,1,...,0,0,0,73,2,0,75,44.000000,56.000000,97.333333
10,JUNIN,CIUDAD DEL CERRO,P.QUINUA,8,6,14,17,19,36,0,...,0,0,0,50,0,0,50,50.000000,50.000000,100.000000
11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10,12,22,0,...,0,0,0,24,6,0,30,60.000000,40.000000,80.000000
12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38,32,70,0,...,0,0,0,96,0,0,96,47.916667,52.083333,100.000000
13,JUNIN,CIUDAD DEL CERRO,H.SAN ANDRÉS,8,0,8,17,25,42,3,...,0,0,0,44,6,0,50,50.000000,50.000000,88.000000
47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,265,...,0,0,63,117,662,0,842,26.484561,22.090261,13.895487
48,JUNIN,JAUJA,A.CHUNÁN,12,11,23,45,21,66,28,...,0,0,0,89,0,0,89,35.955056,22.471910,100.000000
49,JUNIN,JAUJA,C.PACAPACHA,1,7,8,24,18,42,17,...,0,0,0,50,0,0,50,50.000000,18.000000,100.000000
50,JUNIN,JAUJA,HUANCAS,3,2,5,29,40,69,13,...,0,0,0,74,0,0,74,56.756757,17.567568,100.000000
51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,84,...,0,0,0,195,55,0,250,49.600000,37.600000,78.000000
52,JUNIN,JAUJA,PACA,1,4,5,84,52,136,75,...,0,0,6,141,0,0,141,39.716312,21.985816,100.000000
53,JUNIN,JAUJA,MASMA,27,15,42,148,139,287,90,...,0,0,0,294,29,0,329,45.592705,29.483283,89.361702
54,JUNIN,JAUJA,ATAURA,24,22,46,74,68,142,37,...,0,0,0,104,84,0,188,43.617021,24.468085,55.319149
55,JUNIN,JAUJA,HUALÁ,9,9,18,57,28,85,39,...,0,0,0,99,4,0,103,35.922330,63.106796,96.116505
56,JUNIN,JAUJA,JULCÁN,19,11,30,106,144,250,82,...,0,0,0,178,72,0,250,50.000000,22.000000,71.200000
57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,42,...,0,0,0,240,8,0,248,45.967742,40.322581,96.774194
58,JUNIN,JAUJA,A.PAUCÁN,21,13,34,85,69,154,49,...,0,0,0,65,123,0,188,43.617021,34.042553,34.574468
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,0,0,0,333,27,0,360,38.611111,33.333333,92.500000
75,JUNIN,ACOLLA,MARCO,16,12,28,94,55,149,34,...,0,0,0,167,10,0,177,37.853107,24.293785,94.350282
76,JUNIN,ACOLLA,TRAGADERO,20,13,33,87,52,139,67,...,0,0,0,169,3,0,172,37.790698,34.883721,98.255814
77,JUNIN,ACOLLA,CHOCÓN,2,0,2,16,22,38,2,...,0,0,0,40,0,0,40,55.000000,45.000000,100.000000
78,JUNIN,ACOLLA,ACAYA,2,2,4,29,21,50,7,...,0,0,0,54,0,0,54,42.592593,51.851852,100.000000
79,JUNIN,ACOLLA,YAUJAILLO,11,2,13,13,4,17,3,...,0,0,0,30,0,0,30,20.000000,63.333333,100.000000
80,JUNIN,ACOLLA,CURICACA,8,3,11,25,10,35,18,...,0,0,0,46,0,0,46,28.260870,19.565217,100.000000
96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,82,...,0,0,0,141,282,0,423,12.056738,6.855792,33.333333
97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,54,...,0,0,0,183,65,0,248,49.596774,30.241935,73.790323
98,JUNIN,CONCEPCIÓN,HUANTAR,3,0,3,47,41,88,34,...,0,0,0,90,1,0,91,45.054945,1.098901,98.901099
99,JUNIN,CONCEPCIÓN,A.ALAYO,3,8,11,22,29,51,13,...,0,0,0,62,0,0,62,59.677419,6.451613,100.000000
100,JUNIN,CONCEPCIÓN,C.SAN ANTONIO DE CARICANCHO,10,8,18,68,46,114,28,...,0,0,0,132,0,0,132,40.909091,45.454545,100.000000
101,JUNIN,CONCEPCIÓN,SANTO DOMINGO,16,11,27,30,41,71,2,...,0,0,0,98,0,0,98,53.061224,43.877551,100.000000
121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,162,...,0,0,348,157,72,0,577,48.526863,51.473137,27.209705
122,JUNIN,SAN GERÓNIMO,HUALHUAS,20,20,40,92,90,182,40,...,0,0,222,0,0,0,222,49.099099,50.450450,0.000000
123,JUNIN,SAN GERÓNIMO,SAN PEDRO DE SAÑO,19,13,32,73,57,130,55,...,0,0,50,64,48,0,162,42.592593,37.654321,39.506173
124,JUNIN,SAN GERÓNIMO,QUICHUAY,13,19,32,62,56,118,31,...,0,0,59,26,65,0,150,50.000000,39.333333,17.333333
125,JUNIN,SAN GERÓNIMO,CASACANCHA,10,9,19,28,27,55,16,...,0,0,31,35,8,0,74,48.648649,51.351351,47.297297
126,JUNIN,SAN GERÓNIMO,A.INGENIO,18,6,24,77,75,152,45,...,0,0,57,72,47,0,176,46.022727,53.977273,40.909091
127,JUNIN,SAN GERÓNIMO,P.SANTA CRUZ DE QUILCAY,21,20,41,101,84,185,20,...,0,0,31,42,153,0,226,46.017699,40.707965,18.584071
128,JUNIN,SAN GERÓNIMO,RANGRA,7,1,8,26,12,38,15,...,0,0,13,33,0,0,46,28.260870,58.695652,71.739130
161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,258,...,3,1,158,189,689,1,1037,32.979749,22.565092,18.225651
162,JUNIN,TARMA,MACO,28,12,40,72,52,124,36,...,0,0,0,164,0,0,164,39.024390,1.219512,100.000000
163,JUNIN,TARMA,MULLUERO,11,14,25,114,73,187,25,...,0,0,0,179,33,0,212,41.037736,58.490566,84.433962
164,JUNIN,TARMA,ANDAMARCA,7,6,13,68,52,120,41,...,0,0,0,91,42,0,133,42.857143,50.375940,68.421053
165,JUNIN,TARMA,CHANCHA,17,20,37,122,77,199,28,...,0,0,0,228,8,0,236,41.101695,25.000000,96.610169
166,JUNIN,TARMA,TARMATAMBO,3,1,4,72,32,104,29,...,0,0,0,108,0,0,108,30.555556,69.444444,100.000000
181,JUNIN,OROYA,P.OROYA,11,9,20,41,35,76,19,...,0,0,15,28,53,0,96,21.875000,36.458333,29.166667
182,JUNIN,OROYA,HUAYNACANCHA,4,2,6,11,16,27,0,...,0,0,0,33,0,0,33,54.545455,45.454545,100.000000
183,JUNIN,OROYA,PACHA,2,4,6,7,3,10,0,...,0,0,0,16,0,0,16,43.750000,56.250000,100.000000
184,JUNIN,OROYA,HUAYHUAY,13,8,21,55,33,88,47,...,0,0,0,108,1,0,109,37.614679,19.266055,99.082569

###### b. Ciudades con una cantidad de niños (4-6 años) mayor a 50 y de (6-14 años) > 70

In [87]:
junin1 = junin1[( junin1['4_6_years_total'] > 50 ) & (junin['6_14_years_total'] > 70)]
junin1

C:\Users\PERSONAL\AppData\Local\Temp/ipykernel_14472/985548408.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  junin1 = junin1[( junin1['4_6_years_total'] > 50 ) & (junin['6_14_years_total'] > 70)]

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,foreign_men,foreign_women,whites,natives,mestizos,blacks,Total_poblacion,%_women_nread_nwrite,%_men_nread_nwrite,%_natives
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,1,1,4,284,290,1,579,32.469775,51.986183,49.050086
47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,265,...,0,0,63,117,662,0,842,26.484561,22.090261,13.895487
51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,84,...,0,0,0,195,55,0,250,49.600000,37.600000,78.000000
57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,42,...,0,0,0,240,8,0,248,45.967742,40.322581,96.774194
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,0,0,0,333,27,0,360,38.611111,33.333333,92.500000
96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,82,...,0,0,0,141,282,0,423,12.056738,6.855792,33.333333
97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,54,...,0,0,0,183,65,0,248,49.596774,30.241935,73.790323
121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,162,...,0,0,348,157,72,0,577,48.526863,51.473137,27.209705
161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,258,...,3,1,158,189,689,1,1037,32.979749,22.565092,18.225651

###### c. Ordenar las variables según el total de la población y cantidad de población nativa

In [88]:
junin1 = junin1.sort_values(["Total_poblacion", "natives"])   # Sort ascending by default
junin1

,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,...,foreign_men,foreign_women,whites,natives,mestizos,blacks,Total_poblacion,%_women_nread_nwrite,%_men_nread_nwrite,%_natives
97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,54,...,0,0,0,183,65,0,248,49.596774,30.241935,73.790323
57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,42,...,0,0,0,240,8,0,248,45.967742,40.322581,96.774194
51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,84,...,0,0,0,195,55,0,250,49.600000,37.600000,78.000000
74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,66,...,0,0,0,333,27,0,360,38.611111,33.333333,92.500000
96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,82,...,0,0,0,141,282,0,423,12.056738,6.855792,33.333333
121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,162,...,0,0,348,157,72,0,577,48.526863,51.473137,27.209705
0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,158,...,1,1,4,284,290,1,579,32.469775,51.986183,49.050086
47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,265,...,0,0,63,117,662,0,842,26.484561,22.090261,13.895487
161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,258,...,3,1,158,189,689,1,1037,32.979749,22.565092,18.225651

###### d. Solo quedarse con las variables trabajadas en 8, Distrito, y comunidad.

In [89]:
junin1 = junin1[['District','comunidad','%_women_nread_nwrite','%_men_nread_nwrite','Total_poblacion']]
junin1

,District,comunidad,%_women_nread_nwrite,%_men_nread_nwrite,Total_poblacion
97,CONCEPCIÓN,SANTA ROSA DE OCOPA,49.596774,30.241935,248
57,JAUJA,P.RICRÁN,45.967742,40.322581,248
51,JAUJA,A.HUERTAS,49.600000,37.600000,250
74,ACOLLA,P.ACOLLA,38.611111,33.333333,360
96,CONCEPCIÓN,P.CONCEPCIÓN,12.056738,6.855792,423
121,SAN GERÓNIMO,P.SAN GERÓNIMO,48.526863,51.473137,577
0,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,32.469775,51.986183,579
47,JAUJA,P.JAUJA,26.484561,22.090261,842
161,TARMA,P.TARMA,32.979749,22.565092,1037

###### e. Guardar la mitad de la información en bases diferentes (llamar a cada uno Base1 y Base 2)

In [93]:
base1 = junin1.iloc[0:5,:]
base1

,District,comunidad,%_women_nread_nwrite,%_men_nread_nwrite,Total_poblacion
97,CONCEPCIÓN,SANTA ROSA DE OCOPA,49.596774,30.241935,248
57,JAUJA,P.RICRÁN,45.967742,40.322581,248
51,JAUJA,A.HUERTAS,49.600000,37.600000,250
74,ACOLLA,P.ACOLLA,38.611111,33.333333,360
96,CONCEPCIÓN,P.CONCEPCIÓN,12.056738,6.855792,423

In [98]:
base2 = junin1.iloc[5:10,:]
base2

,District,comunidad,%_women_nread_nwrite,%_men_nread_nwrite,Total_poblacion
121,SAN GERÓNIMO,P.SAN GERÓNIMO,48.526863,51.473137,577
0,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,32.469775,51.986183,579
47,JAUJA,P.JAUJA,26.484561,22.090261,842
161,TARMA,P.TARMA,32.979749,22.565092,1037

In [99]:
base1.to_csv("../base1_WG1.csv")
base1.to_excel("../base1_WG1.xlsx")

##### Pregunta 10: Crear una función que me permita extraer columnas un rango de columnas y de filas. Crear una función que me permite extraer una columna según el nombre de la variable y dos filas.